# Site settings
title: The Best Motherfucking Website
email: resir014@gmail.com
url: https://thebestmotherfuckingwebsite.co
baseurl: ""
description: "Your motherfucking websites got nothing compared to this beauty."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#42dca3'

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/resir014
  - title: github
    url: https://github.com/resir014

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["Makefile", "Gruntfile.js", "Gemfile", "README", "LICENSE", "tasks", "node_modules", "package.json"]
keep_files: [".htaccess"]

# Jekyll plugins
gems:
  - jekyll-gist
  - jekyll-sitemap
